//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the build system.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;
using System.Runtime.InteropServices;

[assembly: ComVisible(false)]
[assembly: AssemblyTitle("Templar")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyProduct("Templar")]
[assembly: AssemblyCopyright("Copyright (c) Mattias Rydengren 2013")]
[assembly: AssemblyVersion("0.1")]
[assembly: AssemblyInformationalVersion("0.1")]
[assembly: AssemblyFileVersion("0.1")]
[assembly: AssemblyDelaySign(false)]
